Added session support, broke some stuff
Testing summary:
	 'chat' - FAILED (Invalid cookie error)
	 'dropdown' - FAILED (  File "/Users/jyelewis/Dropbox/dev/pyForms/pyForms/controls/Dropdown.py", line 43, in selectedValue
    return getItemValue(self.dataSource[self.selectedIndex])
TypeError: list indices must be integers, not NoneType

I think the drop down error is becuase the dropdown now returns None if no item is selected (the list is empty))
	 'file' - Passed
	 'index' - Passed
	 'loopTesting' - Passed
	 'nestedLoops' - Passed
	 'repeaterValidators' - Passed
	 'session' - Passed
	 'validation' - Passed

Summary notes:
Cookies broken, drop downs broken